export async function getToken(user: string, password: string) {
    const response = await fetch(`https://chattryoutautogeneratedauthservice-4810.twil.io/login?identity=${user}&password=${password}`);
    const strToken = await response.text();
    console.log(`strToken=${strToken}`);
    return strToken;
}