/* Initialization */
import { Client } from "@twilio/conversations";
import { getToken } from "./getToken";
// user = 'user1';
// pass = 'cadSfzu4L0C@X6M'
// let strToken = fetch(`https://chattryoutautogeneratedauthservice-4810.twil.io/login?identity=${user1}&password=${password}`)
getToken('user1', 'cadSfzu4L0C@X6M').then((result) => {
    console.log(`result = ${result}`)
    let strToken = result;
    const client = new Client(strToken);
    client.on("stateChanged", (state) => {
        console.log(state);

        if (state === "failed") {
            // The client failed to initialize
            return;
        }

        if (state === "initialized") {
            // Use the client
        }
    });

})


