# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c992d655ebe2eaf43baa1597e1c3e656"
name = "shop-app-learn"
handle = "shop-app-learn"
application_url = "https://sword-soft-powell-structured.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-cf436f3b.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://sword-soft-powell-structured.trycloudflare.com/auth/callback",
  "https://sword-soft-powell-structured.trycloudflare.com/auth/shopify/callback",
  "https://sword-soft-powell-structured.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
