print(type(10))
print(type(10.0))
print(type(1+10j))

print(type('This is a string'))
print(type([1,2,3,4]))
print(type((1,2,3,4)))
print(type({'id':1,'name':'Summer Fang'}))
print(type({'Orange','Apple'}))
print(type(frozenset({'Orange','Apple'})))
print(type(range(10)))

print(type(True))
print(type(b'Hello'))
print(type(bytearray(5)))
print(type(memoryview(bytes(5))))
